AWSTemplateFormatVersion: '2010-09-09'
Description: 'CFN IAM Role template'
Parameters:
  iamRole:
    Description: 'CFN IAM role name'
    Type: String
  principalAccountId:
    Description: 'Account Id for role principal'
    Type: String

Resources:
  CfnRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: 'Allow'
            Principal:
              AWS: !Ref principalAccountId
            Action:
              - "sts:AssumeRole"
      Path: '/'
      Policies:
        -
          PolicyName: 'cfn_policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: 'Allow'
                Action:
                  - 'elb:CreateLoadBalancer'
                  - 'elb:CreateTargetGroup'
                  - 'elb:RegisterTargets'
                  - 'elb:CreateListener'
                  - 'elb:DeleteLoadBalancer'
                  - 'elb:DeleteTargetGroup'
                  - 'ec2:StartInstances'
                  - 'ec2:RunInstances'
                  - 'ec2:StopInstances'
                  - 'ec2:TerminateInstances'
                  - 'ec2:CreateSecurityGroup'
                  - 'ec2:DeleteSecurityGroup'
                  - 'ec2:AuthorizeSecurityGroup*'
                  - 'ec2:RevokeSecurityGroup*'
                  - 'ec2:UpdateSecurityGroup*'
                  - 'ec2:AttachVolume'
                  - 'ec2:DetachVolume'
                  - 'ec2:CreateVolume'
                  - 'ec2:DeleteVolume'
                  - 'ec2:Describe*'
                  - 'cloudformation:*'
                  - 's3:*'
                  - 'rds:CreateDBInstance'
                  - 'rds:DeleteDbInstance'
                Resource: '*'
      RoleName: !Ref iamRole
